apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  pipelines:
  - name: audit-default
    inputRefs:
    - audit
    outputRefs:
    - default
  - name: infrastructure-default
    inputRefs:
    - infrastructure
    outputRefs:
    - default
  - name: application-default
    inputRefs:
    - application
    outputRefs:
    - default
